### ISSUE TITLE
CSV w/ Empty Last Line causes ECONNRESET for short files.

### ISSUE THREAD

**Issue by EricByers** [Keyang/node-csvtojson#137]
We have been using v1.0.3 without issue, upgraded to 1.1.3 and have been having issues.

On a really short CSV file, if there is a trailing line break (i.e. last line empty), it will throw a ECONNRESET error.  

From digging into it, it looks like the csvLineBuffer gets set to empty (via setPartial) and because of this when _flush is called it doesn't wait until everything is done processing.  I think this is because it could be a partial new line, but essentially any buffer that happens to end on a line break will trigger this, as well as a file that ends on it.

This is a sample CSV we were using
```
code,name
C,Cinema
D,Direct Mail
B,Mobile
O,Online Display
E,Online Video
M,Opt-In Email
X,Outdoor
P,Print
R,Radio
S,Social
T,Television
V,Viral
M,Opt-In Email
X,Outdoor
P,Print
R,Radio
S,Social
T,Television
V,Viral

```

Edit: it seems to work without issue on longer files.  Our current highWaterMark is 10,000.  It also only happens with workerNum > 1

**Comment by Keyang** [comment]
Thanks for the feedback.
If it is possible, could you paste the code you have the problem with as
well?

Thanks,
Keyang

**Comment by mhassan1** [comment]
Is this still an issue?

**Comment by fataltrace** [comment]
Yes

**Comment by cusspvz** [comment]
I'm experiencing this issue too...

```
completed READCTED.csv
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
/app #
```

**Comment by cusspvz** [comment]
Not using the `CLI`, neither the `webServer`, just the node API. The strangest is that we are only experiencing it inside docker containers (alpine image) and not at MacOS.

**Comment by Keyang** [comment]
Close due to no activity
