### ISSUE TITLE
`Error: read ECONNRESET` when workerNum: 2

### ISSUE THREAD

**Issue by lrkwz** [Keyang/node-csvtojson#220]
I have a simple import converter configured with workerNum: 2; it fails badly (small files) 

![image](https://user-images.githubusercontent.com/1025560/32377020-b9f92cb6-c0a6-11e7-989e-76db060c46b3.png)

**Comment by Keyang** [comment]
It would great helpful if you could share your code where trigger the csv parsing.

Thanks,
Keyang

**Comment by lrkwz** [comment]
from `controllers/CartController.js` where bodiedOrder is the actual csv uploaded from user

```js
(...)
  bodiedUpload: function (req, res) {
    let bodiedOrder = req.file('bodiedOrder');

    User.findOne(req.user.id)
      .then(function (user) {
        if (user) {
          let stream = bodiedOrder && bodiedOrder._files[0].stream;
          Cart.findOrCreate({
            customer: user.id,
            state: 'opened'
          }).then(function (order) {
            Cart.insertBigOrder(stream, order, user)
              .then(function (newOrder) {
(...)
```
from `model/Cart.js`

```js
  insertBigOrder: function (stream, order, user,) {
    return Q.Promise(function (resolve, reject) {
      const headers = ['codice_articolo_gima', 'qta', 'codice_interno', 'note'];
      const converter = new Converter({
        delimiter: ';',
        checkColumn: true,
        quote: 'off',
        trim: true,
        //workerNum: 2,
        checkType: false,
      });
      let result = 'order_completed';

      converter.on('end_parsed', function csvConversionEnded() {
        if (order.totProduct > 0) {
          resolve(order);
        } else {
          reject(result);
        }
      });

      converter.on('record_parsed', function csvRecordParsed(record) {
        _.forOwn(record, function (value, key) {
          if (headers.indexOf(key) === -1 || result === 'invalid_csv') {
            sails.log.debug('error key=\'' + key + '\'');
            sails.log.debug('error value=\'' + value + '\'');
            result = 'invalid_csv';
          }
        });

        if (typeof record === 'object') {
          if (typeof record.codice_articolo_gima != 'undefined') {
            order.products[record.codice_articolo_gima] = { 'codice_interno': record.codice_interno, 'quantity': parseInt(record.qta), 'notes': record.note };
            order.totProduct += parseInt(record.qta);
          } else {
            sails.log.error('This is not a valid record:', record);
          }
        }
      });

      converter.on('error', function csvConversionError(err) {
        sails.log.error('Cannot convert file', err);
        reject(err);
      });

      sails.log.debug('Begin parsing', order);
      stream.pipe(converter);
      return order;
    });
  }
```

**Comment by cusspvz** [comment]
I'm experiencing this issue too...

```
completed READCTED.csv
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
/app #
```

**Comment by Keyang** [comment]
Invalid since v2.0.0
