### ISSUE TITLE
Error using fromFile "TypeError: fs.destroy is not a function"

### ISSUE THREAD

**Issue by gdovicak** [Keyang/node-csvtojson#77]
I am trying to convert a csv file to json using convert.fromFile(<file_path>, callback) . When doing this, csvtojson is throwing the following exception (I modified the file paths):

<full path>/node_modules/csvtojson/libs/core/Converter.js:326
        fs.destroy();
           ^

TypeError: fs.destroy is not a function
    at <full_path>/node_modules/csvtojson/libs/core/Converter.js:326:12
    at Converter.<anonymous> (<full_path>/node_modules/csvtojson/libs/core/Converter.js:366:5)
    at Converter.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at Converter.emit (events.js:169:7)
    at writeAfterEnd (_stream_writable.js:161:10)
    at Converter.Writable.write (_stream_writable.js:204:5)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)

Looking at the code, I am unsure what is trying to be accomplished. I don't see any "destroy" methods on the filestream object in the documentation. Is it supposed to be "delete fs;" instead of "fs.destroy();"?

I am happy to submit a pull request for that but I am unsure of what the intent of the "destroy" function is .

Thanks!

**Comment by Keyang** [comment]
Hi
Thanks for pointing it out.
It was added last version.
The purpose is to clean file stream. But it should be rs.destroy
I will put a fix.

Keyang
